### PR TITLE
Add HRRR processing of CAMELS basins

### PR DESCRIPTION
**Pull request by glitt13**
Key change w/r/t AORC: Moved the process_geo_data() function out of generate.py into a separate file geo_proc.py so that it can easily be used by both HRRR and AORC processing.

The HRRR processing is slow (~1 min/day of data/basin, running locally). There may be a potential to gain processing efficiency when calling xr.open_mfdataset(), but there are challenges with data inconsistencies.

### CODE REVIEW

**Comment by glitt13** [comment]
@hellkite500 FYI - [8f99964](https://github.com/jmframe/CIROH_DL_NextGen/pull/8/commits/8f999647a0367fe6d7181b7f037754db614dd2f8) modifies `process_geo_data()` to handle errors better.

**Review by jmframe — APPROVED** [review]
Are you still working on this? There was action as of this morning...

**Comment by glitt13** [comment]
I began processing HRRR data for a couple days across all CAMELS basins and yesterday's commit added an error handling feature to the process_geo_data() function. I presently don't know if there are other errors that will arise with other CAMELS basins - I'm at about 150 and counting at this point. I could work to integrate Nels' latest changes into HRRR processing as well.

**Review by jmframe — APPROVED** [review]
thanks

**Pull request merged**
