### PR TITLE
Process geopackage files locally for HRRR processing

### PR DESCRIPTION
**Pull request by glitt13**
Modified the HRRR processing, which now allows user to point to a local directory containing geopackage files of interest (rather than download gpkg files from hydrofabric). Refer to the config file config_hrrr_localgpkg.yaml for the example. The key here is to ensure `dir_custom_gpkg` and `id_col` are designated appropriately.

### CODE REVIEW

**Comment by glitt13** [comment]
@jmframe Note this also contains the [patch from Nels](https://github.com/jmframe/CIROH_DL_NextGen/pull/21)

**Comment by glitt13** [comment]
@jmframe - things are running smoothly now and individual basin data compiled as a .csv using `post_process_hrrr.py`

**Comment by glitt13** [comment]
@hellkite500 - fyi added the netcdf post-processing (though it's not exactly the same when divide_ids don't exist when processing Andy's gpkg files)

**Comment by jmframe** [comment]
thanks Guy ([glitt13](https://github.com/glitt13))! Should I merge this? Can you add the sample data, and a description of exactly how to generate that sample?

**Pull request merged**
